### ISSUE TITLE
Erreur lors de la première ouverture d'une instance/Atelier

### ISSUE THREAD

**Issue by Farocs** [CRLbazin/agoraexmachina-obsolete#1]
Lors de l'accès pour la première fois avec un navigateur Web à l'application, la page d'accueil se charge bien, mais si on clic sur une instance/Thème/Atelier, une erreur apparait :

<code>Fatal error: Call to a member function execute() on a non-object in /XXX/XXX/www/seeraiwer/agoraexmachina/library/application.class.php on line 56</code>

Une fois cette erreur apparu, il suffit de faire précédent et l'erreur n’apparaît plus.

**Comment by CRLbazin** [comment]
Bonjour Farocs,

Agora Ex Machina est développé avec le framework CUP. (https://github.com/CRLbazin/cup_mvc) 

Le fonctionnement est fortement dépendant des URLs et dans le cas du serveur Seeraiwer, une variable PHPSESSID est injectée par votre serveur dans les URLs. (Et donc, parasite le fonctionnement de l'application)

Pour information, PHP utilise 2 façons de garder une trace des sessions utilisateur : Soit par cookie, soit en passant le PHPSESSID en paramètre des URL. Il est possible de modifier ce fonctionnement dans votre fichier de configuration php.ini.

![Uploading image.png . . .]()

Ce cas n'était pas géré et nous l'avons pris en compte.
Il sera intégré dans la version 0.8 d'AGORA Ex Machina.

**Comment by CRLbazin** [comment]
En attendant, voici un fix rapide.

Remplacez le contenu de votre fichier .htaccess se trouvant dans le répertoire \web par le code suivant : 

``` HTML
<IfModule mod_rewrite.c>
    RewriteEngine On

    #remove PHPSESSID

    RewriteCond %{QUERY_STRING} PHPSESSID=.*$
    RewriteRule .* %{REQUEST_URI}? [R=301,L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ app.php [QSA,L]
</IfModule>

```
