### ISSUE TITLE
Délégation - Vote multiple

### ISSUE THREAD

**Issue by Farocs** [CRLbazin/agoraexmachina-obsolete#10]
Dans le cas ou j'ai plusieurs délégations, il pourrait être utile, en plus de pouvoir choisir de manière plus massive les votes :
- Soit de pouvoir voter de la même manière pour tout le monde
- Soit de pouvoir voter pour l'ensemble des gens en une seule fois (via un champ à sélection multiple plutôt qu'une liste à choix unique)

Merci encore pour le travail fournit :)

**Comment by CRLbazin** [comment]
Intégré dans la V0.9
