### ISSUE TITLE
Délégation sur un atelier non fonctionnelle

### ISSUE THREAD

**Issue by Farocs** [CRLbazin/agoraexmachina-obsolete#11]
La délégation par atelier ne fonctionne pas. Quand on attribue une délégation à une personne dans un atelier et pas dans l'ensemble du thème, le système ne fonctionne pas.

Symptômes :

Sur la page Détail de l'Atelier : on lit Délégation reçue de , , , , , (le nombre de virgule ne correspond pas au nombre de délégations).
Lors du vote, des champ blancs apparaissent (impossible de voter avec ses lignes)

Exemple :

![1](https://cloud.githubusercontent.com/assets/6787800/3740352/715f8044-1754-11e4-9ec6-03698953b514.png)

**Comment by CRLbazin** [comment]
Nous n'avons pas reussi à reproduire le bug, mais avons sécurisé / fiabiliser les délégations dans la V0.9.

**Comment by Farocs** [comment]
Possible que se soit un problème de configuration serveur de notre coté, nous validerons cela dès la sortie de la V0.9 ;)
