### ISSUE TITLE
Suggestion - Ordre des onglets dans "détail de l'atelier"

### ISSUE THREAD

**Issue by Farocs** [CRLbazin/agoraexmachina-obsolete#12]
L'ordre pour le moment c'est :
1. Contenu
2. Propositions
3. Forum

Cependant, l'ordre du débat c'est une explication du contenu, puis un débat sur le forum, puis la création des propositions et le vote.

L'ordre plus logique serait :
1. Contenu
2. Forum
3. Propositions

**Comment by CRLbazin** [comment]
Fait :)
