### ISSUE TITLE
Call to undefined method Entity::getSizeW()

### ISSUE THREAD

**Issue by Farocs** [CRLbazin/agoraexmachina-obsolete#19]
Quand on veut éditer un thème (Administration\thèmes puis on clique sur un thème), l'erreur suivante apparait :

Fatal error: Call to undefined method applications\modules\instances\entities\categoriesEntity::getSizeW() in /home/seeraiwe/www/seeraiwer/agoraexmachina/applications/modules/instances/forms/categoriesForm.class.php on line 43

Testable sur http://www.seeraiwer.org/agoraexmachina/web/

**Comment by CRLbazin** [comment]
Fix avec la nouvelle version. 0.9.1

(le problème vient du nom du fichier categoriesEntity.class.php.
Il faut enlever le C majuscule à Class
categoriesEntity.Class.php en categoriesEntity.class.php)
