### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by Graf63** [CRLbazin/agoraexmachina-obsolete#22]
Bonjour,

Lors de l'install, il n'y a aucune ligne dans la création des tables.
J'ai un problème par la suite avec l'impossibilité d'accéder au front (in back) avec un nombre de redirections infinies.
Merci

**Comment by CRLbazin** [comment]
Bonjour,

J'ai réinstalllé sur un PC vierge sans problème. 

Pour le problème de base de données : 
- Avez-vous lancé le script SQL "script-installation-database.sql" ? 
- Avez-vous des tables créées dans votre base de données ? 
- Quelle base utilisez-vous ?

Pour le nombre de redirection infinie : 
- Pouvez-vous vider le cache de votre navigateur ? (Ce n'est probablement pas ça, mais sait-on jamais...)
- Pouvez-vous vérifier votre fichier de config.xml ? 
- Pouvez-vous regarder ou me transmettre les logs de votre serveur web ?
