### ISSUE TITLE
2 3 suggestions

### ISSUE THREAD

**Issue by qwertygc** [CRLbazin/agoraexmachina-obsolete#3]
Salut !
2 3 suggestions : 
- mettre un lien sur le github dans le footer ( AGORA Ex Machina est une plateforme [...] sous licence]
- Faire un espace "wiki" permettant l'écriture collaboratif de texte
- Faire un menu modifiable (espace vers un site...)
- impossible en simple utilisateur (ni en administrateur) de téléverser une image quand on crée un atelier
- Arrêt des votes (impossibilité de voter) après l'expiration de la date de l'atelier
- Permettre de créer des "modérateurs d'atelier" qui auront les mêmes droits que les administrateurs mais uniquement dans un atelier précis.
- EDIT : faire un outil permettant de rédiger une synthèse de l'atelier (avec éventuellement un vote pour voir l'approbation général)
- EDIT : voir le % de vote positif, négatif, nul d'une proposition.
  Voilà et merci pour cet outil :)

**Comment by qwertygc** [comment]
En test sur fennek.io : quand je vais sur /register, page blanche. Pas de soucis en localhost.

**Comment by CRLbazin** [comment]
Bonjour Qwertygc, 

Au lieu du titre "2 3 suggestions", j'aurai dit "8 9 suggestions" :)

En tout cas merci pour ta participation.

Mes réponses arrivent. 

Cordialement.

**Comment by CRLbazin** [comment]
> mettre un lien sur le github dans le footer ( AGORA Ex Machina est une plateforme [...] sous licence]

Fait, sera intégré dans la version 0.8

**Comment by CRLbazin** [comment]
> Faire un espace "wiki" permettant l'écriture collaboratif de texte

Pour nous, c'était le but (entre autre) des forums. 
Il faudra peut être repenser la présentation pour inciter les utilisateurs à l'utiliser dans ce sens.

**Comment by CRLbazin** [comment]
> Arrêt des votes (impossibilité de voter) après l'expiration de la date de l'atelier
> Permettre de créer des "modérateurs d'atelier" qui auront les mêmes droits que les administrateurs mais uniquement dans un atelier précis.
> EDIT : faire un outil permettant de rédiger une synthèse de l'atelier (avec éventuellement un vote pour voir l'approbation général)
> EDIT : voir le % de vote positif, négatif, nul d'une proposition. 

Toutes ces fonctionnalitées seront intégrées dans la version 0.9.

Grosso modo : 
La v0.8 comprendra le système de délégation.
La v0.9 comprendra le processus de vote finalisé (Différents modes de vote, comptage, graphs, etc.)
La V1.0 comprendra la sécurité
