### ISSUE TITLE
Suggestion : Automatisation des règles de votes par Thème

### ISSUE THREAD

**Issue by Farocs** [CRLbazin/agoraexmachina-obsolete#4]
Chaque Thème devrait avoir son propre paramétrage sur les règles de vote, par exemple :
1. Choix libre parmi les méthodes de vote
2. Choix restreint parmi les méthodes de vote
3. Aucun Choix parmi mes méthodes de vote

**Comment by CRLbazin** [comment]
Toutes ces fonctionnalitées seront intégrées dans la version 0.9.

Grosso modo : 
La v0.8 comprendra le système de délégation.
La v0.9 comprendra le processus de vote finalisé (Différents modes de vote, comptage, graphs, etc.)
La V1.0 comprendra la sécurité
