### ISSUE TITLE
Suggestion : Possibilité d'avoir une date de cloture commune pour les votes

### ISSUE THREAD

**Issue by Farocs** [CRLbazin/agoraexmachina-obsolete#5]
Dans un Thème, un réglage devrait permettre :
1. D'avoir des dates libres pour la fin du vote de chaque proposition
2. D'avoir un "délai"/Fin de vote commun

Pour le point 2, ule réglage d'un thème demanderait deux informations :
1. La répétitivité du vote (le 1er de chaque mois, le 15 des mois impaire, tout les 3 mois)
2. Le délai minimum de débat/Vote (par exemple : si le débat sur un vote est de moins de 15 jours, alors il ne sera pas voté à l'échéance qui arrive mais à la prochaine)

**Comment by CRLbazin** [comment]
Toutes ces fonctionnalitées seront intégrées dans la version 0.9.

Grosso modo : 
La v0.8 comprendra le système de délégation.
La v0.9 comprendra le processus de vote finalisé (Différents modes de vote, comptage, graphs, etc.)
La V1.0 comprendra la sécurité
