### ISSUE TITLE
Champ "Date de création" Vide pour les utilisateurs (Users & Admin)

### ISSUE THREAD

**Issue by Farocs** [CRLbazin/agoraexmachina-obsolete#7]
Dans les formulaires d'édition de son profil (ou des profils utilisateur par un compte administrateur) il y a un champ "Date de création" sans aucune information.
Le champ est vide aussi dans la base de donnée.

Soit le champ est  à supprimé, soit a renseigner lors de l'inscription (testé avec une inscription en V0.8 sans résultat).

**Comment by CRLbazin** [comment]
Fix dans la V0.9
