### ISSUE TITLE
Erreur lors du lien activation du compte

### ISSUE THREAD

**Issue by Farocs** [CRLbazin/agoraexmachina-obsolete#8]
Après l'inscription d'un utilisateur, il reçoit un e-mail pour activer le compte (pour le moment sans effet, le compte est actif immédiatement).

Quand on clique sur le lien, une erreur apparaît :

Fatal error: Call to a member function execute() on a non-object in /home/seeraiwe/www/seeraiwer/agoraexmachina/library/application.class.php on line 55

Même après un reload ;)

**Comment by CRLbazin** [comment]
Fix, dans la V0.9.
